### ISSUE TITLE
Permissions to cloned files

### ISSUE THREAD

**Issue by ArqTras** [ivoryguru/aeonwallet#2]
Did you try to build from fresh cloned repo ?
I have multiple issues related to permissions or missed files
After change permissions and allow to write build starting :D
Will see how it goes

**Comment by ArqTras** [comment]
Other point, mayby consider to use oryginal aeon repo and just path cmake for zmq modules. Other than main official repo for build might cause less trust. Just my thoughts

**Comment by ArqTras** [comment]
Hmm my side say .. 
https://imgur.com/a/jDqiSJn

**Comment by ivoryguru** [comment]
Thanks for the suggestions. 

Yeah I would like to fix that but I don't know very much about the building and compiling aspects. 99% of the build scripts are copied from xmrwallet. The problem as I see it is writing to `/opt/android/` requires sudo and executing the make file as sudo causes all the permission errors. Either the android folder needs permissions or the build scripts.  After you get through the permissions things will be smooth. 

Also for the zmq/cmake, I agree it would be preferable to get directly from main repo.  If you know how to add that to the scripts it would be appreciated. Otherwise it will be some time before I add that. I was just glad to get it working.

**Comment by ivoryguru** [comment]
> Hmm my side say ..
> https://imgur.com/a/jDqiSJn


Ah, right please add to wallet2_api.h
namespace Aeon = Bitmonero;

**Comment by ArqTras** [comment]
> 
> 
> > Hmm my side say ..
> > https://imgur.com/a/jDqiSJn
> 
> Ah, right please add to wallet2_api.h
> namespace Aeon = Bitmonero;

Yeah that fixed compilation issue 👍

**Comment by ivoryguru** [comment]
Cool. I think you are in the clear.

**Comment by ivoryguru** [comment]
https://github.com/ivoryguru/aeonwallet/commit/3cafc00bf5d56f259c79e04f617223406c51eb92
